import { calculateProjection } from './utils';
import { useState } from "react";
import "./App.css";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import html2pdf from "html2pdf.js";

export default function FinanceCalculator() {
  // These are state variables - they store data that can change
  const [initialAmount, setInitialAmount] = useState(5000);
  const [monthlyContribution, setMonthlyContribution] = useState(500);
  const [years, setYears] = useState(20);
  const [currency, setCurrency] = useState("EUR");
  const [returnRate, setReturnRate] = useState(7);
  const [scenarios, setScenarios] = useState([]);
  const [scenarioName, setScenarioName] = useState("");
  const [scenarioCount, setScenarioCount] = useState(0);

  // This object maps currency codes to their symbols for display
  const currencySymbols = { EUR: "€", USD: "$", RSD: "дин" };
  const symbol = currencySymbols[currency];

  // This func calculates how much monet you'll have each yeat
  // It takse: starting money, monthly addition, number of years, and expected return rate



  // This function saves the current setup as a scenario
  const addScenario = () => {
    if (!scenarioName.trim()) return;

    const finalValue = projection[projection.length - 1].balance;

    const newScenario = {
      id: scenarioCount, // Use counter instead of Math.random()
      name: scenarioName,
      finalValue: finalValue,
      monthly: monthlyContribution,
      rate: returnRate,
    };

    setScenarios([...scenarios, newScenario]);
    setScenarioCount(scenarioCount + 1); // Increment the counter
    setScenarioName("");
  };

  // This function removes a scenario by its ID
  const removeScenario = (id) => {
    setScenarios(scenarios.filter((s) => s.id !== id));
  };
  // Call the function with current values and store results
  const projection = calculateProjection(
    initialAmount,
    monthlyContribution,
    years,
    returnRate,
  );

  // This function generates and downloads a PDF report

  const exportPDF = () => {
    // Create a temporary HTML element to hold our report content

    const reportContent = document.createElement("div");
    reportContent.style.padding = "20px";
    reportContent.style.fontFamily = "Arial, sans-serif";
    reportContent.style.fontSize = "12px";

    // Build the HTML content for the PDF
    reportContent.innerHTML = `
      <h1 style="margin-top: 0;">Personal Finance Projection Report</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      
      <h2>Current Setup</h2>
      <p><strong>Currency:</strong> ${currency}</p>
      <p><strong>Starting Amount:</strong> ${symbol}${initialAmount.toLocaleString()}</p>
      <p><strong>Monthly Contribution:</strong> ${symbol}${monthlyContribution.toLocaleString()}</p>
      <p><strong>Time Horizon:</strong> ${years} years</p>
      <p><strong>Expected Return:</strong> ${returnRate}%</p>

      <h2>Results After ${years} Years</h2>
      <p><strong>Total Balance:</strong> ${symbol}${projection[projection.length - 1].balance.toLocaleString()}</p>
      <p><strong>Your Contributions:</strong> ${symbol}${projection[projection.length - 1].principal.toLocaleString()}</p>
      <p><strong>Investment Growth:</strong> ${symbol}${(projection[projection.length - 1].balance - projection[projection.length - 1].principal).toLocaleString()}</p>

      ${
        scenarios.length > 0
          ? `
        <h2>Saved Scenarios</h2>
        <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
          <tr style="border-bottom: 2px solid #333;">
            <th style="text-align: left; padding: 8px;">Scenario Name</th>
            <th style="text-align: right; padding: 8px;">Final Value</th>
            <th style="text-align: right; padding: 8px;">Monthly</th>
            <th style="text-align: right; padding: 8px;">Return</th>
          </tr>
          ${scenarios
            .map(
              (s) => `
            <tr style="border-bottom: 1px solid #ddd;">
              <td style="padding: 8px;">${s.name}</td>
              <td style="text-align: right; padding: 8px;">${symbol}${s.finalValue.toLocaleString()}</td>
              <td style="text-align: right; padding: 8px;">${symbol}${s.monthly.toLocaleString()}</td>
              <td style="text-align: right; padding: 8px;">${s.rate}%</td>
            </tr>
          `,
            )
            .join("")}
        </table>
      `
          : ""
      }

      <p style="margin-top: 30px; font-size: 10px; color: #666; border-top: 1px solid #ddd; padding-top: 10px;">
        This report was generated by the Personal Finance Calculator. Values are estimates based on the inputs provided.
      </p>
    `;

    // Create PDF settings
    const opt = {
      margin: 10,
      filename: "finance-projection.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { orientation: "portrait", unit: "mm", format: "a4" },
    };

    // Generate and download the PDF
    html2pdf().set(opt).from(reportContent).save();
  };

  // Create data for the bar chart (current + all saved scenarios)
  const barData = [
    { name: "Current", value: projection[projection.length - 1].balance },
    ...scenarios.map((s) => ({ name: s.name, value: s.finalValue })),
  ];

  return (
    <div style={{ padding: "2rem", fontFamily: "sans-serif" }}>
      <h1>Personal Finance Calculator</h1>

      {/* LEFT PANEL - All the input controls */}
      <div style={{ maxWidth: "400px", marginBottom: "2rem" }}>
        {/* INPUT 1: Starting Amount */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.5rem",
              fontWeight: "bold",
            }}
          >
            Starting amount ({currency})
          </label>

          {/* Slider - drag to adjust, ranges from 0 to 100,000 */}
          <input
            type="range"
            min="0"
            max="100000"
            step="1000"
            value={initialAmount}
            onChange={(e) => setInitialAmount(Number(e.target.value))}
            style={{ width: "100%", marginBottom: "0.5rem" }}
          />

          {/* Number input - type exact numbers */}
          <input
            type="number"
            value={initialAmount}
            onChange={(e) => setInitialAmount(Number(e.target.value))}
            style={{ width: "100%", padding: "0.5rem", marginBottom: "0.5rem" }}
          />

          {/* Display the current value */}
          <div
            style={{ fontSize: "18px", fontWeight: "bold", color: "#0F766E" }}
          >
            {symbol}
            {initialAmount.toLocaleString()}
          </div>
        </div>

        {/* INPUT 2: Monthly Contribution */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.5rem",
              fontWeight: "bold",
            }}
          >
            Monthly contribution ({currency})
          </label>

          <input
            type="range"
            min="0"
            max="5000"
            step="50"
            value={monthlyContribution}
            onChange={(e) => setMonthlyContribution(Number(e.target.value))}
            style={{ width: "100%", marginBottom: "0.5rem" }}
          />

          <input
            type="number"
            value={monthlyContribution}
            onChange={(e) => setMonthlyContribution(Number(e.target.value))}
            style={{ width: "100%", padding: "0.5rem", marginBottom: "0.5rem" }}
          />

          <div
            style={{ fontSize: "18px", fontWeight: "bold", color: "#0F766E" }}
          >
            {symbol}
            {monthlyContribution.toLocaleString()}
          </div>
        </div>

        {/* INPUT 3: Years */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.5rem",
              fontWeight: "bold",
            }}
          >
            Time horizon (years)
          </label>

          <input
            type="range"
            min="1"
            max="30"
            step="1"
            value={years}
            onChange={(e) => setYears(Number(e.target.value))}
            style={{ width: "100%", marginBottom: "0.5rem" }}
          />

          <input
            type="number"
            value={years}
            onChange={(e) => setYears(Number(e.target.value))}
            style={{ width: "100%", padding: "0.5rem", marginBottom: "0.5rem" }}
          />

          <div
            style={{ fontSize: "18px", fontWeight: "bold", color: "#0F766E" }}
          >
            {years} years
          </div>
        </div>

        {/* INPUT 4: Currency Dropdown */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.5rem",
              fontWeight: "bold",
            }}
          >
            Currency
          </label>

          {/* Select dropdown - user picks which currency to use */}
          <select
            value={currency}
            onChange={(e) => setCurrency(e.target.value)}
            style={{ width: "100%", padding: "0.5rem", fontSize: "14px" }}
          >
            <option value="EUR">EUR (€)</option>
            <option value="USD">USD ($)</option>
            <option value="RSD">RSD (дин)</option>
          </select>
        </div>

        {/* INPUT 5: Return Rate Buttons */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.75rem",
              fontWeight: "bold",
            }}
          >
            Expected return
          </label>

          {/* Three buttons for different risk levels */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 1fr",
              gap: "8px",
            }}
          >
            {/* Conservative button */}
            <button
              onClick={() => setReturnRate(4)}
              style={{
                padding: "0.5rem",
                backgroundColor: returnRate === 4 ? "#0F766E" : "#f0f0f0",
                color: returnRate === 4 ? "white" : "black",
                border: "none",
                cursor: "pointer",
                borderRadius: "4px",
                fontWeight: "bold",
              }}
            >
              Conservative (4%)
            </button>

            {/* Moderate button */}
            <button
              onClick={() => setReturnRate(7)}
              style={{
                padding: "0.5rem",
                backgroundColor: returnRate === 7 ? "#0F766E" : "#f0f0f0",
                color: returnRate === 7 ? "white" : "black",
                border: "none",
                cursor: "pointer",
                borderRadius: "4px",
                fontWeight: "bold",
              }}
            >
              Moderate (7%)
            </button>

            {/* Aggressive button */}
            <button
              onClick={() => setReturnRate(10)}
              style={{
                padding: "0.5rem",
                backgroundColor: returnRate === 10 ? "#0F766E" : "#f0f0f0",
                color: returnRate === 10 ? "white" : "black",
                border: "none",
                cursor: "pointer",
                borderRadius: "4px",
                fontWeight: "bold",
              }}
            >
              Aggressive (10%)
            </button>
          </div>

          {/* Show which rate is selected */}
          <div
            style={{ marginTop: "0.75rem", fontSize: "14px", color: "#666" }}
          >
            Selected: {returnRate}%
          </div>
        </div>
      </div>
      {/* Chart Section */}

      <div style={{ marginTop: "3rem" }}>
        <h2>Growth projection</h2>

        {/* Container for the chart - height is 400px */}

        <ResponsiveContainer width="100%" height={400}>
          {/* The chart itself - data is our projection array */}
          <LineChart data={projection}>
            {/* Grid lines for better readability */}
            <CartesianGrid strokeDasharray="3 3" />

            {/* Bottom axis - shows years */}
            <XAxis
              dataKey="year"
              label={{
                value: "Years",
                position: "insideBottomRight",
                offset: -5,
              }}
            />

            {/* Left axis - shows balance */}
            <YAxis
              label={{
                value: `Balance (${symbol})`,
                angle: -90,
                position: "insideLeft",
              }}
            />

            {/* Tooltip shows details when hovering over points */}
            <Tooltip
              formatter={(value) =>
                `${symbol}${Math.round(value).toLocaleString()}`
              }
              labelFormatter={(label) => `Year: ${label}`}
            />

            {/* Legend to differentiate lines */}
            <Legend />
            {/* First line - your total balance (teal color) */}
            <Line
              type="monotone"
              dataKey="balance"
              stroke="#0F766E"
              strokeWidth={2}
              dot={false}
              name="Total balance"
            />

            {/* Second line - how much you contributed (amber color) */}
            <Line
              type="monotone"
              dataKey="principal"
              stroke="#D97706"
              strokeWidth={2}
              dot={false}
              name="Your contributions"
            />
          </LineChart>
        </ResponsiveContainer>

        {/* Show final numbers */}
        <div
          style={{
            marginTop: "1rem",
            padding: "1rem",
            backgroundColor: "#f5f5f5",
          }}
        >
          <h3>After {years} years:</h3>
          <p>
            <strong>Total balance:</strong> {symbol}
            {projection[projection.length - 1].balance.toLocaleString()}
          </p>
          <p>
            <strong>Your contributions:</strong> {symbol}
            {projection[projection.length - 1].principal.toLocaleString()}
          </p>
          <p>
            <strong>Investment growth:</strong> {symbol}
            {(
              projection[projection.length - 1].balance -
              projection[projection.length - 1].principal
            ).toLocaleString()}
          </p>
        </div>
      </div>

      {/* SCENARIOS SECTION */}
      <div
        style={{
          marginTop: "3rem",
          padding: "1.5rem",
          backgroundColor: "#f9f9f9",
          borderRadius: "8px",
        }}
      >
        <h2>Compare scenarios</h2>

        {/* Input to name a scenario + button to save it */}
        <div style={{ display: "flex", gap: "12px", marginBottom: "1.5rem" }}>
          {/* Text input for scenario name */}
          <input
            type="text"
            placeholder="Name this scenario (e.g., 'Conservative plan')"
            value={scenarioName}
            onChange={(e) => setScenarioName(e.target.value)}
            onKeyPress={(e) => e.key === "Enter" && addScenario()} // Save on Enter key
            style={{
              flex: 1,
              padding: "0.75rem",
              fontSize: "14px",
              border: "1px solid #ddd",
              borderRadius: "4px",
            }}
          />

          {/* Button to save the scenario */}
          <button
            onClick={addScenario}
            disabled={!scenarioName.trim()} // Disable if name is empty
            style={{
              padding: "0.75rem 1.5rem",
              backgroundColor: scenarioName.trim() ? "#0F766E" : "#ccc",
              color: "white",
              border: "none",
              borderRadius: "4px",
              fontWeight: "bold",
              cursor: scenarioName.trim() ? "pointer" : "not-allowed",
            }}
          >
            Save scenario
          </button>

          
        </div>
        {/* PDF EXPORT BUTTON */}
      <div style={{ marginTop: '2rem', paddingTop: '2rem', borderTop: '1px solid #ddd' }}>
        <button
          onClick={exportPDF}
          style={{
            padding: '0.75rem 1.5rem',
            backgroundColor: '#D97706',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            fontWeight: 'bold',
            cursor: 'pointer',
            fontSize: '14px',
          }}
        >
          📄 Export as PDF
        </button>
      </div>

        {/* Only show this section if there are saved scenarios */}
        {scenarios.length > 0 && (
          <div>
            {/* List of saved scenarios */}
            <div style={{ marginBottom: "2rem" }}>
              <h3>Saved scenarios:</h3>
              <div style={{ display: "grid", gap: "10px" }}>
                {scenarios.map((scenario) => (
                  <div
                    key={scenario.id}
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      padding: "1rem",
                      backgroundColor: "white",
                      border: "1px solid #ddd",
                      borderRadius: "4px",
                    }}
                  >
                    {/* Scenario info */}
                    <div>
                      <div style={{ fontWeight: "bold", fontSize: "14px" }}>
                        {scenario.name}
                      </div>
                      <div style={{ fontSize: "12px", color: "#666" }}>
                        {symbol}
                        {scenario.finalValue.toLocaleString()} •{" "}
                        {scenario.monthly} {currency}/mo • {scenario.rate}%
                      </div>
                    </div>

                    {/* Delete button */}
                    <button
                      onClick={() => removeScenario(scenario.id)}
                      style={{
                        padding: "0.5rem 1rem",
                        backgroundColor: "#ff6b6b",
                        color: "white",
                        border: "none",
                        borderRadius: "4px",
                        cursor: "pointer",
                        fontSize: "12px",
                      }}
                    >
                      Remove
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Bar chart comparing all scenarios */}
            <div>
              <h3>Final values comparison</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={barData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis
                    label={{
                      value: "Amount",
                      angle: -90,
                      position: "insideLeft",
                    }}
                  />
                  <Tooltip
                    formatter={(value) =>
                      `${symbol}${Math.round(value).toLocaleString()}`
                    }
                  />
                  <Bar dataKey="value" fill="#0F766E" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
